### ISSUE TITLE
Add option to have image for questions and 0 or more images for answerOptions

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#10]
Let's add an option to have an image for the _question_
and 0 or more images for the _answerOptions_

![image](https://user-images.githubusercontent.com/850878/37346640-36d0e2d2-26a6-11e8-9178-f0adf5394b8c.png)

in all cases, **imageSrc** should not be required. (not for **question** or **answerOption**)
If there's no imageSrc prop present, 
or the prop has a "" value,  
we should render the _answerOption_ text content alone. 

@rogertheriault wrote:

> And it seems with no answer image we’d want to Make the label full width. 

Not necessarily. When the labels are right-aligned & styled correctly, the different label lengths look / feel good.

![image](https://user-images.githubusercontent.com/850878/37347064-5d472be6-26a7-11e8-877e-6611a3ec9e67.png)

**Comment by smcnally** [comment]
Looks good / is WaD:
- Handles Question image - **CHECK**
- Handles all combos of image present / not: - **CHECK**
-- question image; no img for answer options
-- no question image
-- some answer options w image; some without
			
- the answer attribute "**type**" flashes on the screen on submit -- 
more apparent without images
`style display: none` is likely best there. (we do like having, seeing , passing that **type** attribute) 

![180314-iq-image_handling_updates](https://user-images.githubusercontent.com/850878/37435838-67fc24a0-27bb-11e8-94be-b02df2d4d021.gif)


- that and other styling issues should be done once we merge the style changes from smc-mozilla. 
		
Wanna review / comment on / approve that?
https://github.com/smcnally/office_quiz/pull/12

**Comment by rogertheriault** [comment]
#12 is approved and merged. Seems the flashing issue you noted above happens only with FFox. But it's been resolved - the img tag won't be output in the AnswerOption if there's no such property (or it's effectively empty)

**Comment by smcnally** [comment]
All is Well as of https://github.com/smcnally/office_quiz/pull/11
