### ISSUE TITLE
Longer question span; align labels left for answer options without images

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#13]
* `.question span` should have a max width of > 189. 

* left-justify `answerOptionContainer` / `radioCustomLabel` (or create new class) when `answerOption` has no image

![image](https://user-images.githubusercontent.com/850878/37833204-2165139a-2e81-11e8-9dab-59f6ec6da37f.png)

![image](https://user-images.githubusercontent.com/850878/37833272-451eba7a-2e81-11e8-8746-1a496f4fdab0.png)

![image](https://user-images.githubusercontent.com/850878/37833219-2871eeba-2e81-11e8-9465-e10fec7c8308.png)

![image](https://user-images.githubusercontent.com/850878/37833186-15c703ea-2e81-11e8-985e-bcffbe97eb4f.png)

**Comment by rogertheriault** [comment]
I'm going to tackle this - I'm going to see if we can use css grid instead of the :before elements that seem to be hard to override

**Comment by rogertheriault** [comment]
The question area should be good now for all combinations.

Re the justification - do you want the non-image rounded rects to all start at the left edge of the column? i.e.
```
| [ o foo bar ]
| [ o foolishness and a longer sentence ]
| [ o short ]
| [ o way too long yes this is gonna wrap 
|    and then some...                                  ]
```

**Comment by rogertheriault** [comment]
for example, like this?
![image](https://user-images.githubusercontent.com/294707/37851492-7b904446-2eb5-11e8-82b4-1dd0095c4691.png)

**Comment by rogertheriault** [comment]
ok, the latest change should address the bubbles for both with and without images. The without images version omits the entire image container, and uses inline bubbles. The with images has an extra class and uses the absolute positioning we've been using all along. I didn't have to fiddle with the stuff inside the answer option (i.e., :before is still there)

**Comment by rogertheriault** [comment]
![image](https://user-images.githubusercontent.com/294707/37852285-6c21a8e4-2eb8-11e8-9561-d53d67686e3e.png)
![image](https://user-images.githubusercontent.com/294707/37852299-7bf8e0ca-2eb8-11e8-9aff-d110f747c2be.png)

**Comment by smcnally** [comment]
Perfetto - merged
