### ISSUE TITLE
Optional Sounds when answer is selected

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#14]
Add option for playing audio on `answerOption` selection

Audio is optional and scoped per `question` or per `answerOption` in **quizQuestion.js** config files. 

When scoped to a question, all selected answerOptions would play the same sound (_sound.mp3_):

```
        question: "This is my Question",
        imageSrc: "image.gif",
        soundSrc: "sound.mp3",
```
When scoped to `answerOption`, the specified sound would play when that `answerOption` is selected (and would override any `soundSrc` scoped to its `question`):

```
       answers: [
            {
                type: { njinsider: 1, finance: 1 },
                content: "$1 - $2 Million",
                imageSrc: ""
                soundSrc: "answer1Sound.mp3",
            },
```
In all cases, if the `soundSrc` attribute is not present or has a null or blank value, we skip it.  

This is using native `audioObject.play()` capes of ~modern browsers -- no additional libs or frameworks.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

**Comment by rogertheriault** [comment]
I found this game using a simple audio api. https://react.rocks/example/react-trivia - good example code.

However, it has all the audio pre-installed. Dynamically getting audio might be glitchy but I can tackle that if necessary. Do we need a different sound per answer option from the beginning or is a general sound effect sufficient?

**Comment by smcnally** [comment]
Will have a look at that example code. Strong preference is to use native audio capes in modern browsers vs any additional api / libs / framework

`audioObject.play() `

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

https://www.w3schools.com/jsreF/tryit.asp?filename=tryjsref_audio_play

> Do we need a different sound per answer option from the beginning or is a general sound effect sufficient?

The same sound for all answer options will be great.
