### ISSUE TITLE
answerOptions images and radio buttons 

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#2]
- answer option images should have their own div and fill 100% of it
- radio selects should overlap the upper-left of the answer option images 
- add a white bg to the radio selects to distinguish it from the image

**Comment by smcnally** [comment]
Using this execution as example:
https://meanbusiness.com/shepherd/cannabisfeminist/

![image](https://user-images.githubusercontent.com/850878/35490132-5dff27ae-046b-11e8-9125-f9f8c971d868.png)


Along these lines is better:
![image](https://user-images.githubusercontent.com/850878/35490421-83c7072a-046d-11e8-9cd0-c52c24ecb37b.png)

- Image is centered; some consistent padding all around
- radio and answer label float on the image


Too many of these elements are currently handled by the same [`radioCustomLabel`](https://github.com/smcnally/office_quiz/blob/master/src/index.css#L121) style.

**Comment by rogertheriault** [comment]
Sorted in https://github.com/smcnally/office_quiz/pull/4
