### ISSUE TITLE
All questions should start at top of screen

### ISSUE THREAD

**Issue by smcnally** [smcnally/office_quiz#8]
On questions 2+, we should always start at the top - always start from / scroll to top 

especially when the previous question has longer list of answer options, questions 2+ start partially "scrolled" / at other than the top.

_(NB - This is not new behavior. current functionality was introduced before January)_

**Comment by rogertheriault** [comment]
I added a likely fix for this in my refactor branch just now
https://github.com/smcnally/office_quiz/pull/6/commits/3e68385fbcd49415d4c0e46a9b2cc564c13511e7
